#http://www.akc.org/dog-breeds/groups/
Groups = [
    'Hearding',
    'Hound',
    'NonSporting',
    'Sporting',
    'Terrier',
    'Toy',
    'Working',
    'Foundation Stock Service',
    'Miscellaneous'
]

#http://www.akc.org/dog-breeds/groups/herding/
Hearding = [
    'Australian Cattle Dog',
    'Australian Shepherd',
    'Bearded Collie',
    'Beauceron',
    'Belgian Malinois',
    'Belgian Sheepdog',
    'Belgian Tervuren',
    'Bergamasco',
    'Border Collie',
    'Bouvier Des Flandres',
    'Briard',
    'Canaan Dog',
    'Cardigan Welsh Corgi',
    'Collie',
    'Entlebucher Mountain Dog',
    'Finnish Lapphund',
    'German Shepherd Dog',
    'Icelandic Sheepdog',
    'Norwegian Buhund',
    'Old English Sheepdog',
    'Pembroke Welsh Corgi',
    'Polish Lowland Sheepdog',
    'Puli',
    'Pyrenean Shepherd',
    'Shetland Sheepdog',
    'Spanish Water Dog',
    'Swedish Vallhund'
]

#http://www.akc.org/dog-breeds/groups/hound/
Hound = [
    'Afghan Hound',
    'American English Coonhound',
    'American Foxhound',
    'Basenji',
    'Basset Hound',
    'Beagle',
    'Black and Tan Coonhound',
    'Bloodhound',
    'Bluetick Coonhound',
    'Borzoi',
    'Cirneco Dell-Etna',
    'Dachshund',
    'English Foxhound',
    'Greyhound',
    'Harrier',
    'Ibizan Hound',
    'Irish Wolfhound',
    'Norwegian Elkhound',
    'Otterhound',
    'Petit Basset Griffon Vendeen',
    'Pharaoh Hound',
    'Plott',
    'Portuguese Podengo Pequeno',
    'Redbone Coonhound',
    'Rhodesian Ridgeback',
    'Saluki',
    'Scottish Deerhound',
    'Treeing Walker Coonhound',
    'Whippet'
]

#http://www.akc.org/dog-breeds/groups/non-sporting/
NonSporting = [
    'American Eskimo Dog',
    'Bichon Frise',
    'Boston Terrier',
    'Bulldog',
    'Chinese Shar-Pei',
    'Chow Chow',
    'Coton De Tulear',
    'Dalmatian',
    'Finnish Spitz',
    'French Bulldog',
    'Keeshond',
    'Lhasa Apso',
    'Lowchen',
    'Norwegian Lundehund',
    'Poodle',
    'Schipperke',
    'Shiba Inu',
    'Tibetan Spaniel',
    'Tibetan Terrier',
    'Xoloitzcuintli'
]

#http://www.akc.org/dog-breeds/groups/sporting/
Sporting = [
    'American Water Spaniel',
    'Boykin Spaniel',
    'Brittany',
    'Chesapeake Bay Retriever',
    'Clumber Spaniel',
    'Cocker Spaniel',
    'Curly-Coated Retriever',
    'English Cocker Spaniel',
    'English Setter',
    'English Springer Spaniel',
    'Field Spaniel',
    'Flat-Coated Retriever',
    'German Shorthaired Pointer',
    'German Wirehaired Pointer',
    'Golden Retriever',
    'Gordon Setter',
    'Irish Red And White Setter'
    'Irish Setter',
    'Irish Water Spaniel',
    'Labrador Retriever',
    'Nova Scotia Duck Tolling Retriever',
    'Pointer',
    'Spinone Italiano',
    'Sussex Spaniel',
    'Vizsla',
    'Weimaraner',
    'Welsh Springer Spaniel',
    'Wirehaired Pointing Griffon',
    'Wirehaired Vizsla'
]

#http://www.akc.org/dog-breeds/groups/terrier/
Terrier = [
    'Airedale Terrier',
    'American Staffordshire Terrier',
    'Australian Terrier',
    'Bedlington Terrier',
    'Border Terrier',
    'Bull Terrier',
    'Cairn Terrier',
    'Cesky Terrier',
    'Dandie Dinmont Terrier',
    'Glen of Imaal Terrier',
    'Irish Terrier',
    'Kerry Blue Terrier',
    'Lakeland Terrier',
    'Manchester Terrier',
    'Miniature Bull Terrier',
    'Miniature Schnauzer',
    'Norfolk Terrier',
    'Norwich Terrier',
    'Parson Russell Terrier',
    'Rat Terrier',
    'Russell Terrier',
    'Scottish Terrier',
    'Sealyham Terrier',
    'Skye Terrier',
    'Smooth Fox Terrier',
    'Soft Coated Wheaten Terrier',
    'Staffordshire Bull Terrier',
    'Welsh Terrier',
    'West Highland White Terrier',
    'Wire Fox Terrier'
]

#http://www.akc.org/dog-breeds/groups/toy/
Toy = [
    'Affenpinscher',
    'Brussels Griffon',
    'Cavalier King Charles Spaniel',
    'Chihuahua',
    'Chinese Crested',
    'English Toy Spaniel',
    'Havanese',
    'Italian Greyhound',
    'Japanese Chin',
    'Maltese',
    'Manchester Terrier',
    'Miniature Pinscher',
    'Papillon',
    'Pekingese',
    'Pomeranian',
    'Poodle',
    'Pug',
    'Shih Tzu',
    'Silky Terrier',
    'Toy Fox Terrier',
    'Yorkshire Terrier'
]

#http://www.akc.org/dog-breeds/groups/working/
Working = [
    'Akita',
    'Alaskan Malamute',
    'Anatolian Shepherd Dog',
    'Bernese Mountain Dog',
    'Black Russian Terrier',
    'Boerboel',
    'Boxer',
    'Bullmastiff',
    'Cane Corso',
    'Chinook',
    'Doberman Pinscher',
    'Dogue de Bordeaux',
    'German Pinscher',
    'Giant Schnauzer',
    'Great Dane',
    'Great Pyrenees',
    'Greater Swiss Mountain Dog',
    'Komondor',
    'Kuvasz',
    'Leonberger',
    'Mastiff',
    'Neapolitan Mastiff',
    'Newfoundland',
    'Portuguese Water Dog',
    'Rottweiler',
    'Samoyed',
    'Siberian Husky',
    'Standard Schnauzer',
    'Tibetan Mastiff',
    'St. Bernard'
]

#http://www.akc.org/dog-breeds/groups/foundation-stock-service/
FoundationStockService = [
    'American Hairless Terrier',
    'American Leopard Hound',
    'Appenzeller Sennenhunde',
    'Barbet',
    'Basset Fauve de Bretagne',
    'Belgian Laekenois',
    'Berger Picard',
    'Biewer Terrier',
    'Bolognese',
    'Bracco Italiano',
    'Braque du Bourbonnais',
    'Broholmer',
    'Catahoula Leopard Dog',
    'Caucasian Ovcharka',
    'Central Asian Shepherd Dog',
    'Czechoslovakian Vlcak',
    'Danish-Swedish Farmdog',
    'Deutscher Wachtelhund',
    'Dogo Argentino',
    'Drentsche Patrijshond',
    'Drever',
    'Dutch Shepherd',
    'Estrela Mountain Dog',
    'Eurasier',
    'French Spaniel',
    'German Longhaired Pointer',
    'German Spitz',
    'Grand Basset Griffon Vendeen',
    'Hamiltonstovare',
    'Hovawart',
    'Jagdterrier',
    'Jindo',
    'Kai Ken',
    'Karelian Bear Dog',
    'Kishu Ken',
    'Nederlandse Kooikerhondje',
    'Kromfohrlander',
    'Lagotto Romagnolo',
    'Lancashire Heeler',
    'Miniature American Shepherd',
    'Mudi',
    'Norrbottenspets',
    'Perro de Presa Canario',
    'Peruvian Inca Orchid',
    'Portuguese Podengo',
    'Portuguese Pointer',
    'Portuguese Sheepdog',
    'Pumi',
    'Pyrenean Mastiff',
    'Rafeiro do Alentejo',
    'Russian Toy',
    'Russian Tsvetnaya Bolonka',
    'Schapendoes',
    'Shikoku',
    'Slovensky Cuvac',
    'Sloughi',
    'Small Munsterlander Pointer',
    'Spanish Mastiff',
    'Stabyhoun',
    'Swedish Lapphund',
    'Thai Ridgeback',
    'Tornjak',
    'Tosa',
    'Transylvanian Hound',
    'Treeing Tennessee Brindle',
    'Working Kelpie'
]

#http://www.akc.org/dog-breeds/groups/miscellaneous-class/
Miscellaneous = [
    'American Hairless Terrier',
    'Azawakh',
    'Belgian Laekenois',
    'Berger Picard',
    'Dogo Argentino',
    'Grand Basset Griffon Vendeen',
    'Lagotto Romagnolo',
    'Miniature American Shepherd',
    'Norrbottenspets',
    'Peruvian Inca Orchid',
    'Portuguese Podengo',
    'Pumi',
    'Sloughi'
]

#http://www.dogsindepth.com/overview/dog_coat_color_chart.html
Color = [
    'Blue Merle',
    'Charcoal',
    'Chestnut',
    'Chocolate',
    'Cream',
    'Fawn',
    'Gold',
    'Grizzle',
    'Gray',
    'Harlequin',
    'Lemon',
    'Light Brown',
    'Liver',
    'Mohogany',
    'Mustard',
    'Nearly Black',
    'Off White',
    'Orange Roan',
    'Orange',
    'Orange and White',
    'Parti-Color',
    'Peppered',
    'Pied',
    'Red',
    'Red-Black Brindle',
    'Red Tick',
    'Red and White',
    'Ruby',
    'Rust',
    'Sable',
    'Salt and Pepper',
    'Sandy',
    'Silver',
    'Tan',
    'Tan Brindle',
    'Tri-Color',
    'Weimaraner Blue',
    'Wheaten',
    'White',
    'Wild Boar',
    'Wolf Color',
    'Yellow'
]
